"""
api.py - SovereignNode AI: FastAPI Inference Bridge
====================================================
Wraps rag_engine.query_rag() behind a REST API so the Java ingestion
service can call the AI inference engine over HTTP.

Endpoints:
  POST /generate-insight    Generate a diagnostic insight from telemetry
  GET  /health              Liveness check
  GET  /docs                Swagger UI (auto-generated by FastAPI)

Run:
  uvicorn api:app --host 0.0.0.0 --port 8000 --workers 1
  (single worker: the LLM is not thread-safe; use multiple processes if needed)
"""

from __future__ import annotations

import logging
import time
import threading
from typing import List, Optional

_inference_lock = threading.Lock()

import torch
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator

from config import cfg
from rag_engine import query_rag, RAGResult

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=cfg.LOG_LEVEL,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------
app = FastAPI(
    title="SovereignNode AI - Inference Engine",
    description=(
        "Offline RAG inference API for industrial IoT anomaly diagnostics. "
        "Reads from enterprise maintenance manuals stored in ChromaDB and "
        "generates grounded diagnostic insights using a local quantized SLM."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # Restrict to Java service IP in production
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Pydantic schemas (JSON contract with the Java Spring Boot client)
# ---------------------------------------------------------------------------

class RawTelemetry(BaseModel):
    """Raw sensor observation snapshot embedded in the insight request."""
    temperature: float = Field(..., description="Temperature in degrees Celsius", ge=-50, le=1200)
    vibration:   float = Field(..., description="Vibration in mm/s RMS", ge=0, le=1000)
    timestamp:   str   = Field(..., description="ISO-8601 UTC observation timestamp",
                                example="2026-04-23T17:00:00.000Z")


class InsightRequest(BaseModel):
    """
    Payload sent by the Java Spring Boot TelemetryIngestionService
    when a sensor anomaly is detected.
    """
    sensor_id:    str          = Field(..., min_length=1, max_length=64,
                                        description="Unique sensor hardware ID")
    anomaly_type: str          = Field(..., description="Anomaly category",
                                        example="HIGH_VIBRATION")
    raw_telemetry: RawTelemetry = Field(..., description="Telemetry snapshot at anomaly time")
    query:        str          = Field(..., min_length=10, max_length=2000,
                                        description="Natural language diagnostic query")

    @field_validator("sensor_id")
    @classmethod
    def sensor_id_alphanumeric(cls, v: str) -> str:
        import re
        if not re.match(r"^[A-Za-z0-9_\-]+$", v):
            raise ValueError("sensor_id must only contain alphanumerics, hyphens, underscores")
        return v


class InsightResponse(BaseModel):
    """
    Response returned to the Java Spring Boot client.
    Must match the AiInferenceClient.AiInsightResponse Java record exactly.
    """
    insight:             str         = Field(..., description="LLM-generated diagnostic insight")
    confidence_score:    float       = Field(..., ge=0.0, le=1.0,
                                             description="Average cosine similarity of retrieved chunks")
    sources_referenced:  List[str]   = Field(..., description="Source document filenames used as context")
    inference_time_ms:   float       = Field(..., description="End-to-end inference latency in milliseconds")


# ---------------------------------------------------------------------------
# Helper: derive a confidence score from retrieval similarities
# ---------------------------------------------------------------------------

def _compute_confidence(result: RAGResult) -> float:
    """
    Derive a [0, 1] confidence score from the average similarity of
    retrieved chunks. Returns 0.0 if no chunks were retrieved.
    """
    if not result.retrieved_chunks:
        return 0.0
    avg = sum(c.similarity_score for c in result.retrieved_chunks) / len(result.retrieved_chunks)
    return round(min(1.0, max(0.0, avg)), 4)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Operations"])
async def health_check() -> dict:
    """Liveness endpoint. Returns device info and model configuration."""
    return {
        "status": "healthy",
        "model_id": cfg.LLM_MODEL_ID,
        "embedding_model": cfg.EMBEDDING_MODEL_NAME,
        "cuda_available": torch.cuda.is_available(),
        "cuda_device": torch.cuda.get_device_name(0) if torch.cuda.is_available() else "N/A",
        "chroma_collection": cfg.CHROMA_COLLECTION_NAME,
        "top_k_results": cfg.TOP_K_RESULTS,
    }


@app.post(
    "/generate-insight",
    response_model=InsightResponse,
    status_code=200,
    tags=["Inference"],
    summary="Generate a diagnostic insight from sensor telemetry",
    description=(
        "Accepts a telemetry anomaly payload from the Java ingestion service. "
        "Retrieves the top-K most relevant passages from the enterprise manual "
        "vector store, builds a grounded prompt, and returns an LLM-generated "
        "diagnostic insight. All inference is performed entirely offline."
    ),
)
def generate_insight(request: InsightRequest) -> InsightResponse:
    """
    Full RAG pipeline endpoint.

    Injects telemetry context into the RAG query so the retrieved passages
    and generated answer are grounded in both the enterprise documentation
    AND the specific sensor readings at anomaly time.
    """
    # Enrich the user query with precise telemetry context
    enriched_query = (
        f"{request.query} "
        f"[Context: sensor={request.sensor_id}, "
        f"anomaly_type={request.anomaly_type}, "
        f"temperature={request.raw_telemetry.temperature}C, "
        f"vibration={request.raw_telemetry.vibration}mm/s, "
        f"timestamp={request.raw_telemetry.timestamp}]"
    )

    logger.info(
        "Insight request: sensor_id=%s anomaly_type=%s vibration=%.2f temp=%.1f",
        request.sensor_id,
        request.anomaly_type,
        request.raw_telemetry.vibration,
        request.raw_telemetry.temperature,
    )

    t0 = time.perf_counter()
    try:
        with _inference_lock:
            result: RAGResult = query_rag(enriched_query, top_k=cfg.TOP_K_RESULTS)
    except Exception as exc:
        logger.exception("RAG pipeline failed for sensor_id=%s", request.sensor_id)
        raise HTTPException(
            status_code=500,
            detail=f"Inference engine error: {str(exc)}"
        )

    inference_ms = (time.perf_counter() - t0) * 1000.0
    confidence   = _compute_confidence(result)

    logger.info(
        "Insight generated: sensor_id=%s confidence=%.3f sources=%s inference_ms=%.0f",
        request.sensor_id,
        confidence,
        result.sources,
        inference_ms,
    )

    return InsightResponse(
        insight=result.answer,
        confidence_score=confidence,
        sources_referenced=result.sources,
        inference_time_ms=round(inference_ms, 2),
    )


# ---------------------------------------------------------------------------
# Global exception handler
# ---------------------------------------------------------------------------

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    logger.exception("Unhandled exception on %s %s", request.method, request.url)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal inference engine error. Check service logs."},
    )
