"""
api.py - SovereignNode AI: FastAPI Inference Bridge (Ollama Edition)
=====================================================================
Uses Ollama to run Qwen 2.5-3B locally — no GPU required, no HuggingFace
model loading overhead.

Endpoints:
  POST /generate-insight    Generate a diagnostic insight from telemetry (RAG)
  POST /chat                Free-form AI chat with optional RAG context
  GET  /health              Liveness check
  GET  /docs                Swagger UI (auto-generated by FastAPI)

Run:
  uvicorn api:app --host 0.0.0.0 --port 8000 --workers 1
"""

from __future__ import annotations

import logging
import time
import threading
from typing import List, Optional

_inference_lock = threading.Lock()

import requests
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, Field, field_validator

from config import cfg
from rag_engine import query_rag, retrieve, build_prompt, RAGResult, SYSTEM_PROMPT

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=cfg.LOG_LEVEL,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Ollama configuration
# ---------------------------------------------------------------------------
OLLAMA_BASE_URL = cfg.OLLAMA_BASE_URL
OLLAMA_MODEL    = cfg.OLLAMA_MODEL

# ---------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------
app = FastAPI(
    title="SovereignNode AI - Inference Engine",
    description=(
        "Offline RAG inference API for industrial IoT anomaly diagnostics. "
        "Powered by Qwen 2.5-3B via Ollama. Reads from enterprise maintenance "
        "manuals stored in ChromaDB and generates grounded diagnostic insights."
    ),
    version="2.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------

class RawTelemetry(BaseModel):
    temperature: float = Field(..., ge=-50, le=1200)
    vibration:   float = Field(..., ge=0, le=1000)
    timestamp:   str   = Field(...)


class InsightRequest(BaseModel):
    sensor_id:    str          = Field(..., min_length=1, max_length=64)
    anomaly_type: str          = Field(...)
    raw_telemetry: RawTelemetry = Field(...)
    query:        str          = Field(..., min_length=10, max_length=2000)

    @field_validator("sensor_id")
    @classmethod
    def sensor_id_alphanumeric(cls, v: str) -> str:
        import re
        if not re.match(r"^[A-Za-z0-9_\-]+$", v):
            raise ValueError("sensor_id must only contain alphanumerics, hyphens, underscores")
        return v


class InsightResponse(BaseModel):
    insight:             str         = Field(...)
    confidence_score:    float       = Field(..., ge=0.0, le=1.0)
    sources_referenced:  List[str]   = Field(...)
    inference_time_ms:   float       = Field(...)


class ChatMessage(BaseModel):
    role:    str = Field(..., pattern="^(user|assistant|system)$")
    content: str = Field(..., min_length=1)


class ChatRequest(BaseModel):
    """Free-form chat request, optionally grounded in the RAG knowledge base."""
    messages:    List[ChatMessage] = Field(..., min_length=1)
    use_rag:     bool              = Field(default=True,  description="Augment with RAG context")
    stream:      bool              = Field(default=False, description="Stream response tokens")
    top_k:       int               = Field(default=cfg.TOP_K_RESULTS, ge=1, le=10)
    temperature: float             = Field(default=cfg.TEMPERATURE, ge=0.0, le=2.0)


class ChatResponse(BaseModel):
    answer:           str       = Field(...)
    confidence_score: float     = Field(..., ge=0.0, le=1.0)
    sources:          List[str] = Field(...)
    inference_time_ms: float    = Field(...)
    rag_chunks_used:  int       = Field(...)


# ---------------------------------------------------------------------------
# Ollama helper
# ---------------------------------------------------------------------------

def _ollama_chat(
    messages: list[dict],
    stream: bool = False,
    temperature: float = cfg.TEMPERATURE,
) -> str | requests.Response:
    """
    Call the Ollama /api/chat endpoint.
    Returns either a complete string (stream=False) or a streaming Response.
    """
    payload = {
        "model": OLLAMA_MODEL,
        "messages": messages,
        "stream": stream,
        "options": {
            "temperature": temperature,
            "top_p": cfg.TOP_P,
            "repeat_penalty": cfg.REPETITION_PENALTY,
            "num_predict": cfg.MAX_NEW_TOKENS,
        },
    }

    if stream:
        response = requests.post(
            f"{OLLAMA_BASE_URL}/api/chat",
            json=payload,
            stream=True,
            timeout=300,
        )
        response.raise_for_status()
        return response  # caller handles streaming

    response = requests.post(
        f"{OLLAMA_BASE_URL}/api/chat",
        json=payload,
        timeout=300,
    )
    response.raise_for_status()
    data = response.json()
    return data["message"]["content"].strip()


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def _compute_confidence(result: RAGResult) -> float:
    """
    Return the average cross-encoder confidence from the RAGResult.
    Falls back to cosine similarity if reranker was not used.
    """
    if result.avg_confidence > 0:
        return round(min(1.0, max(0.0, result.avg_confidence)), 4)
    # Fallback: average cosine similarity
    if not result.retrieved_chunks:
        return 0.0
    avg = sum(c.similarity_score for c in result.retrieved_chunks) / len(result.retrieved_chunks)
    return round(min(1.0, max(0.0, avg)), 4)


def _compute_confidence_from_chunks(chunks) -> float:
    """Compute confidence from retrieved chunks (uses cross-encoder score if available)."""
    if not chunks:
        return 0.0
    avg = sum(c.confidence for c in chunks) / len(chunks)
    return round(min(1.0, max(0.0, avg)), 4)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Operations"])
async def health_check() -> dict:
    """Liveness endpoint. Returns Ollama model info and configuration."""
    try:
        r = requests.get(f"{OLLAMA_BASE_URL}/api/tags", timeout=5)
        models = [m["name"] for m in r.json().get("models", [])]
        ollama_ok = True
    except Exception:
        models = []
        ollama_ok = False

    return {
        "status": "healthy" if ollama_ok else "degraded",
        "model_id": OLLAMA_MODEL,
        "ollama_url": OLLAMA_BASE_URL,
        "ollama_ok": ollama_ok,
        "available_models": models,
        "embedding_model": cfg.EMBEDDING_MODEL_NAME,
        "chroma_collection": cfg.CHROMA_COLLECTION_NAME,
        "top_k_results": cfg.TOP_K_RESULTS,
        "similarity_threshold": cfg.SIMILARITY_THRESHOLD,
    }


@app.post(
    "/generate-insight",
    response_model=InsightResponse,
    status_code=200,
    tags=["Inference"],
    summary="Generate a diagnostic insight from sensor telemetry (RAG-grounded)",
)
def generate_insight(request: InsightRequest) -> InsightResponse:
    """
    Full RAG pipeline: retrieve manual passages -> build grounded prompt -> Ollama Qwen 2.5-3B.

    KEY DESIGN: RAG retrieval uses ONLY the clean maintenance question (no sensor IDs /
    timestamps) to maximise cosine similarity with the knowledge base. Telemetry
    metadata is injected into the LLM prompt AFTER retrieval as extra_context,
    giving the model full operational data without diluting the retrieval embedding.
    """
    # Retrieval-optimised query — domain keywords, no metadata noise
    retrieval_query = (
        f"{request.query} "
        f"vibration {request.raw_telemetry.vibration:.1f} mm/s "
        f"temperature {request.raw_telemetry.temperature:.0f} degrees Celsius "
        f"{request.anomaly_type.replace('_', ' ').lower()} "
        "bearing alarm threshold maintenance corrective action inspection"
    )

    # Telemetry block injected only into the LLM prompt (not used for vector search)
    telemetry_context = (
        f"LIVE SENSOR DATA:\n"
        f"  Sensor ID:    {request.sensor_id}\n"
        f"  Anomaly Type: {request.anomaly_type}\n"
        f"  Vibration:    {request.raw_telemetry.vibration:.2f} mm/s RMS\n"
        f"  Temperature:  {request.raw_telemetry.temperature:.1f} C\n"
        f"  Timestamp:    {request.raw_telemetry.timestamp}\n"
    )

    logger.info(
        "Insight request: sensor_id=%s anomaly_type=%s vibration=%.2f temp=%.1f",
        request.sensor_id,
        request.anomaly_type,
        request.raw_telemetry.vibration,
        request.raw_telemetry.temperature,
    )

    t0 = time.perf_counter()
    try:
        with _inference_lock:
            result: RAGResult = query_rag(
                retrieval_query,
                top_k=cfg.TOP_K_RESULTS,
                extra_context=telemetry_context,
            )
    except Exception as exc:
        logger.exception("RAG pipeline failed for sensor_id=%s", request.sensor_id)
        raise HTTPException(status_code=500, detail=f"Inference engine error: {str(exc)}")

    inference_ms = (time.perf_counter() - t0) * 1000.0
    confidence   = _compute_confidence(result)

    logger.info(
        "Insight generated: sensor_id=%s confidence=%.3f sources=%s inference_ms=%.0f",
        request.sensor_id, confidence, result.sources, inference_ms,
    )

    return InsightResponse(
        insight=result.answer,
        confidence_score=confidence,
        sources_referenced=result.sources,
        inference_time_ms=round(inference_ms, 2),
    )



@app.post(
    "/chat",
    response_model=ChatResponse,
    status_code=200,
    tags=["Chat"],
    summary="Free-form AI chat with optional RAG grounding",
    description=(
        "Accepts a conversation history and routes the latest user message "
        "through the RAG pipeline (if use_rag=true) to ground the answer in "
        "enterprise documentation. Returns the AI answer with confidence score."
    ),
)
def chat(request: ChatRequest) -> ChatResponse:
    """
    AI chat endpoint — free-form questions answered by Qwen 2.5-3B,
    optionally grounded in the ChromaDB knowledge base.
    """
    # Extract the most recent user message for RAG retrieval
    user_messages = [m for m in request.messages if m.role == "user"]
    if not user_messages:
        raise HTTPException(status_code=400, detail="No user message found in messages list.")

    latest_user_query = user_messages[-1].content

    t0 = time.perf_counter()

    # ── RAG retrieval ───────────────────────────────────────────────────────────
    chunks = []
    confidence = 0.0

    if request.use_rag:
        try:
            chunks = retrieve(latest_user_query, top_k=request.top_k)
            confidence = _compute_confidence_from_chunks(chunks)
            logger.info(
                "Chat RAG: retrieved %d chunks, confidence=%.3f for query='%s'",
                len(chunks), confidence, latest_user_query[:80],
            )
        except Exception as exc:
            logger.warning("RAG retrieval failed, falling back to base LLM: %s", exc)

    # ── Build message list for Ollama ───────────────────────────────────────────
    if chunks:
        # Inject RAG context into the system message
        context_blocks = []
        for i, chunk in enumerate(chunks, start=1):
            context_blocks.append(
                f"[Passage {i}] (Source: {chunk.source_file}, "
                f"similarity: {chunk.similarity_score:.3f})\n{chunk.text}"
            )
        context_str = "\n\n".join(context_blocks)

        system_content = (
            SYSTEM_PROMPT + "\n\n"
            "KNOWLEDGE BASE CONTEXT (use this to answer the question):\n"
            f"{context_str}"
        )
    else:
        # No RAG context — general assistant mode
        system_content = (
            "You are SovereignNode AI, a helpful assistant specializing in "
            "industrial IoT, predictive maintenance, and sensor diagnostics. "
            "Be concise, technically accurate, and professional. "
            "If you don't know something, say so honestly."
        )

    ollama_messages = [{"role": "system", "content": system_content}]

    # Add conversation history (excluding the latest user message — we'll add it last)
    for msg in request.messages[:-1]:
        ollama_messages.append({"role": msg.role, "content": msg.content})

    # Add the latest user message
    ollama_messages.append({"role": "user", "content": latest_user_query})

    # ── Generate answer ─────────────────────────────────────────────────────────
    try:
        answer = _ollama_chat(
            ollama_messages,
            stream=False,
            temperature=request.temperature,
        )
    except requests.exceptions.RequestException as exc:
        logger.exception("Ollama request failed")
        raise HTTPException(status_code=503, detail=f"Ollama service unavailable: {str(exc)}")

    inference_ms = (time.perf_counter() - t0) * 1000.0
    sources = list(dict.fromkeys(c.source_file for c in chunks))

    logger.info(
        "Chat answer generated: confidence=%.3f sources=%s inference_ms=%.0f chars=%d",
        confidence, sources, inference_ms, len(str(answer)),
    )

    return ChatResponse(
        answer=str(answer),
        confidence_score=confidence,
        sources=sources,
        inference_time_ms=round(inference_ms, 2),
        rag_chunks_used=len(chunks),
    )


# ---------------------------------------------------------------------------
# Global exception handler
# ---------------------------------------------------------------------------

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    logger.exception("Unhandled exception on %s %s", request.method, request.url)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal inference engine error. Check service logs."},
    )
